### ISSUE TITLE
How to do this

### ISSUE THREAD

**Issue by AmazingMech2418** [Spaceflyer234/JSON-Editor#1]
https://github.com/Spaceflyer234/JSON-Editor/blob/d61709d51bf096e04fca473bfcfb611be7ac63ed/index.js#L1:L4

Well, first off with fetching, it depends on the environment. You could use fetch or normal XMLHTTPRequests in the browser, Node-Fetch or the https module in Node, the request module in Node, etc. 

For JSON, just use `JSON.parse`!

**Comment by AmazingMech2418** [comment]
One question though is why do this? I mean, hacked blocks don't work with 3.0...

**Comment by Spaceflyer234** [comment]
> One question though is why do this? I mean, hacked blocks don't work with 3.0...

There are still some.

**Comment by Spaceflyer234** [comment]
> https://github.com/Spaceflyer234/JSON-Editor/blob/d61709d51bf096e04fca473bfcfb611be7ac63ed/index.js#L1:L4
> 
> Well, first off with fetching, it depends on the environment. You could use fetch or normal XMLHTTPRequests in the browser, Node-Fetch or the https module in Node, the request module in Node, etc.
> 
> For JSON, just use `JSON.parse`!

Okay, I just need help putting fetched data in a variable.

**Comment by Spaceflyer234** [comment]
Never mind, I figured it out.
